### ISSUE TITLE
Defining the problem

### ISSUE THREAD

**Issue by abaghela** [UBC-MDS/seismophobia#13]
I understand that your team is trying to predict whether a given individual's fear of earthquakes. A better description of demographic information that will be used would be helpful. Also, why is this question important? Will this help governments, individuals...? Which classifiers will you use? Logistic regression, random forests, etc? Will you evaluate the classifier on a held out test set? How will your EDA inform the classification pipeline?

**Comment by jkim222383** [comment]
- Clarify description of demographic information and address significance of research question in README: https://github.com/UBC-MDS/seismophobia/commit/c9919aa995e4cbbabb097033abf0882600595fd7
- Describe methodology in more detail in README: https://github.com/UBC-MDS/seismophobia/commit/06029932511242580b9092bddad91c94d2690881
