### ISSUE TITLE
Code, EDA

### ISSUE THREAD

**Issue by abaghela** [UBC-MDS/seismophobia#14]
Great directory structure, great download script, great use of dplyr, nice code! More comments would be helpful to understand the flow. Also please provide a .md file so we can see the figures.

**Comment by abaghela** [comment]
Also, no spaces in file names.

**Comment by jkim222383** [comment]
- Comments added in subsequent commits to improve readability
- Provide link to rendered html using html preview link: https://github.com/UBC-MDS/seismophobia/commit/14baccc262619cd3564a772299b5d7af0252b1bc
- Rename file to remove white space: https://github.com/UBC-MDS/seismophobia/commit/1ccca8977194ad42a909945860a11e75a5ba3544
