### ISSUE TITLE
Milestone 2: Script 3 (EDA Rmd)

### ISSUE THREAD

**Issue by dbandrews** [UBC-MDS/seismophobia#16]
- Read in processed data from `processed` folder
- Add in histogram of each variable, facetted plot?
- Create visuals, SAVE OUT TO PNG in VISUALS FOLDER....
- Embed visuals, using knitr::include_graphics()

**Comment by dusty736** [comment]
- Added arguments that access data in processed folder, and exports figures in the visuals folder.
- Added histogram of each variable in a facetted plot (very large when I open in github).
- Plots saved as png in the visuals folder.

**Comment by trevorki** [comment]
In `feature_distributions.png`, the top age category reads "60" but I think it should be "60+".

**Comment by trevorki** [comment]
The `target_distribution.png` plot has very thick bars. Could they be made thinner so that the image can be scaled down while keeping the text readable?

**Comment by dusty736** [comment]
Thanks for the input, Trevor.  All great idea.  I made the changes and created a pull request.

**Comment by dusty736** [comment]
Tests have been added checking for proper image file creation.

**Comment by jkim222383** [comment]
EDA script updated: https://github.com/UBC-MDS/seismophobia/commit/7469123355d8eaaa046e33da9685983f0176d88b
EDA visuals changed: https://github.com/UBC-MDS/seismophobia/commit/d0d4b31e8da0391edea3abfb4812bddd854e7e9c
Tests added for image creation as mentioned above: https://github.com/UBC-MDS/seismophobia/commit/2a41a9a8e3cfdcf04821be33be200c9f7fa3c74f
