### ISSUE TITLE
Milestone 2: Script 4( Feature engineering and model selection)

### ISSUE THREAD

**Issue by dbandrews** [UBC-MDS/seismophobia#17]
- Read in train/test splits
- Build pipeline
- Binary classifier then iterate ( Group Extreme Worried, Very Worried, Somewhat Worried  as Target Class)
- Save out a couple model result graphs to visuals folder

NO FEATURE SELECTION!!

Visuals:
- DummyClassifier vs. RandomForestClassifier
- ROC/AUC Curve on Test
- Confusion Matrix
- Feature Importance

**Comment by trevorki** [comment]
Could we get the values of precision and recall in the results table along with the F1 scores?
Not urgent for milestone 2 but probably a goo idea.

**Comment by jkim222383** [comment]
- Model script updated and required visuals generated: https://github.com/UBC-MDS/seismophobia/commit/3fd7a3a21a78a62c4a0c5d2e5570c6fe53606b4c 
- Feature selection removed: https://github.com/UBC-MDS/seismophobia/commit/d40f0d2c6621a225dd5eb4960561e69a72549f39
