### ISSUE TITLE
Milestone 2: Script 5 ( Snazzy results)

### ISSUE THREAD

**Issue by dbandrews** [UBC-MDS/seismophobia#18]
- Rmd format
- Introduction: Importance of our task, use case?
- Question
- Process
- Results
- Interpretation
- 1-2 pages without images/tables/references
- References: Language + Packages cited, 3 more (original 538 article, dataset on Github, another article??)

**Comment by trevorki** [comment]
Should I be including any code in the document or just inserting the image files for the visuals?

**Comment by dbandrews** [comment]
I think you are good to just insert visuals

**Comment by jkim222383** [comment]
- Rmd for generating report updated: https://github.com/UBC-MDS/seismophobia/commit/5bf2b14c342a6fd32b96c5644b3d3469b7d9ab3b
