### ISSUE TITLE
Milestone 2: README updates

### ISSUE THREAD

**Issue by dbandrews** [UBC-MDS/seismophobia#19]
- Short summary
- How to run with scripts, inputs specified for each, order. Flow chart?
- Dependencies (point to a Conda env, Renv)

**Comment by jkim222383** [comment]
- Provide introduction/summary in README: https://github.com/UBC-MDS/seismophobia/commit/c9919aa995e4cbbabb097033abf0882600595fd7
- Provide conda env and Renv set-up instructions and shell script command in README file: https://github.com/UBC-MDS/seismophobia/commit/2f0bb7ec12813384bae2949f653de1408203cc8d
