### ISSUE TITLE
Re-framing of the question

### ISSUE THREAD

**Issue by trevorki** [UBC-MDS/seismophobia#25]
After discussion in lab period, we decided to not use the survey-type questions (rate your knowledge of... etc) and only use the demographic features (_age, gender, income, region_) to predict whether the respondent was afraid of Earthquakes. This is the feature: "_In general, how worried are you about earthquakes?_"

**Comment by jkim222383** [comment]
- Research question re-framed in README: https://github.com/UBC-MDS/seismophobia/commit/c9919aa995e4cbbabb097033abf0882600595fd7
- Survey questions dropped from analysis: https://github.com/UBC-MDS/seismophobia/commit/95d24f95fb0a82c255748f6fcbedbdcb53bf3ffd
