### ISSUE TITLE
Nlme package on Mac is busted

### ISSUE THREAD

**Issue by dbandrews** [UBC-MDS/seismophobia#49]
Nlme is a dependency is one of the other R packages, using this in Renv breaks building the library on mac.

**Comment by dusty736** [comment]
To fix this for Mac, I ran `renv::restore()` using R on the command line.  All packages were loaded properly and running the make file from the command line worked without error.

**Comment by dbandrews** [comment]
Dealt with by Dockerfile in #79 and #74
