### ISSUE TITLE
Milestone 3: SHAP plots of each variable's behavior

### ISSUE THREAD

**Issue by dbandrews** [UBC-MDS/seismophobia#53]

**Comment by dusty736** [comment]
-The SHAP plots work well for Random Forest model.
-It looks like we need to change the code for Logistic Regression to something similar to:
https://shap.readthedocs.io/en/latest/example_notebooks/general/Explainable%20AI%20with%20Shapley%20Values.html#Explaining-a-linear-logistic-regression-model

**Comment by dbandrews** [comment]
Addressed by #56
